texlive-xetex.installed: EXTRA_REV=-r1
texlive-latexrecommended.installed: EXTRA_REV=-r2
texlive-context.installed: EXTRA_REV=-r1
texlive-langindic.installed: EXTRA_REV=-r1
texlive-latex.installed: EXTRA_REV=-r1
texlive-latexextra.installed: EXTRA_REV=-r1
texlive-pictures.installed: EXTRA_REV=-r1
texlive-pstricks.installed: EXTRA_REV=-r1
