#!/usr/bin/env bash
set -eu

# Defines a somewhat sensible order in which packages should be merged
# into ::gentoo.
PACKAGES=(
	dev-libs/kpathsea
	dev-libs/ptexenc

	app-text/dvipsk
	app-text/ttf2pk2
	app-text/ps2pkm
	app-text/dvisvgm

	dev-tex/biblatex
	dev-tex/biber

	dev-tex/latexmk
	dev-tex/glossaries
	dev-tex/tex4ht
	dev-tex/minted
	dev-tex/bibtexu
	dev-tex/pgf
	dev-tex/latex-beamer

	app-text/texlive-core

	dev-texlive/texlive-basic
	dev-texlive/texlive-luatex
	dev-texlive/texlive-latex
	dev-texlive/texlive-latexrecommended
	dev-texlive/texlive-plaingeneric

	dev-texlive/texlive-fontutils
	dev-texlive/texlive-langportuguese
	dev-texlive/texlive-publishers
	dev-texlive/texlive-langpolish
	dev-texlive/texlive-langcyrillic
	dev-texlive/texlive-langspanish
	dev-texlive/texlive-langkorean
	dev-texlive/texlive-langczechslovak
	dev-texlive/texlive-music
	dev-texlive/texlive-pstricks
	dev-texlive/texlive-xetex
	dev-texlive/texlive-langjapanese
	dev-texlive/texlive-fontsextra
	dev-texlive/texlive-langother
	dev-texlive/texlive-formatsextra
	dev-texlive/texlive-langitalian
	dev-texlive/texlive-langfrench
	dev-texlive/texlive-pictures
	dev-texlive/texlive-mathscience
	dev-texlive/texlive-metapost
	dev-texlive/texlive-latexextra
	dev-texlive/texlive-bibtexextra
	dev-texlive/texlive-langarabic
	dev-texlive/texlive-context
	dev-texlive/texlive-fontsrecommended
	dev-texlive/texlive-langgreek
	dev-texlive/texlive-langeuropean
	dev-texlive/texlive-games
	dev-texlive/texlive-langchinese
	dev-texlive/texlive-langenglish
	dev-texlive/texlive-binextra
	dev-texlive/texlive-humanities
	dev-texlive/texlive-langgerman
	dev-texlive/texlive-langcjk

	app-text/texlive
)

GENTOO_DIR="$(portageq get_repo_path / gentoo)"
TEX_OVERLAY_DIR="$(portageq get_repo_path / tex-overlay)"

for PACKAGE in "${PACKAGES[@]}"; do
	SOURCE="${TEX_OVERLAY_DIR}/${PACKAGE}"
	DEST="${GENTOO_DIR}/${PACKAGE}"

	[[ ! -d "${DEST}" ]] && mkdir "${DEST}"

	cp "${SOURCE}"/*.ebuild "${DEST}"
	cp "${SOURCE}"/metadata.xml "${DEST}"
	if [[ -d "${SOURCE}"/files ]]; then
		[[ ! -d "${DEST}"/files ]] && mkdir "${DEST}"/files

		cp "${SOURCE}"/files/* "${DEST}"/files
	fi

	cd "${DEST}"

	git add .

	if git diff-index --quiet @; then
		echo "Nothing to commit for ${PACKAGE}"
		continue
	fi

	pkgdev commit
done
