
PORTDIR=$(shell portageq portdir)
DISTDIR=$(shell portageq distdir)


TEXLIVE_OVERLAY_LOCATION=../../../texlive-overlay

TEXLIVE_LIVE_MOUNTPOINT=/mnt/texlive
TEXLIVE_INST_MOUNTPOINT=/mnt/texlive-inst
CTAN_MIRROR=http://ctan.org/tex-archive
TL_TRUNK=/share/stock/texlive/trunk
TUG=ftp://tug.org/texlive/Images/

MKDIRP=mkdir -p
RMF=rm -f
RMDIR=rmdir
CPF=cp -f
