
PORTDIR=$(shell portageq portdir)
DISTDIR=$(shell portageq distdir)


TEXLIVE_OVERLAY_LOCATION=../../../texlive-overlay

TEXLIVE_LIVE_MOUNTPOINT=/mnt/texlive-live
TEXLIVE_INST_MOUNTPOINT=/mnt/texlive-inst
CTAN_MIRROR=http://ctan.org/tex-archive
TL_TRUNK=/share/stock/texlive/trunk

MKDIRP=mkdir -p
RMF=rm -f
RMDIR=rmdir
CPF=cp -f
